In [1]:
import pandas as pd

In [2]:
df_2021_ocenka = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d002/2021/ocenka.csv")
df_2021_subject = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d002/2021/subject.csv")

In [ ]:
df_2022_subject = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d002/2022/subject.csv")
df_2022_ocenka = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d002/2022/ocenka.csv")

In [ ]:
df_2023_subject = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d002/2023/subject.csv")
df_2023_ocenka = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d002/2023/ocenka.csv")

In [ ]:
df_2024_subject = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d002/2024/subject.csv")
df_2024_ocenka = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d002/2024/ocenka.csv")

In [ ]:
import gc

dfs_to_concat_ocenka = [df_2021_ocenka, df_2022_ocenka, df_2023_ocenka, df_2024_ocenka]
dfs_to_concat_subject = [df_2021_subject, df_2022_subject, df_2023_subject, df_2024_subject]

df_combined_ocenka = pd.concat(dfs_to_concat_ocenka, ignore_index=True, copy=False)
df_combined_subject = pd.concat(dfs_to_concat_subject, ignore_index=True, copy=False)

gc.collect()

0

In [5]:
df_2021_ocenka[df_2021_ocenka['NOMER'] == 2021000001]

,GODO,TE,K,NOMP,POL,VOZ,GR1,GR2,GR3,GR4,...,GR319_2,GR319_3,GR319_4,GR319_5,GR319_6,GR319_7,GR319_8,GR319_9,GR319_10,NOMER
0,2021,19,1,2,2,39,3,2,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021000001

In [6]:
df_2021_subject[df_2021_subject['NOMER'] == 2021000001]

,GODO,TE,K,NOMP,POL,VOZ,GR1,GR2,GR3,GR4,...,GR192,GR193,GR194,GR195,GR196,GR201,GR202,GR21,GR22,NOMER
0,2021,19,1,2,2,72,10,10,5,8,...,8,8,8,8,89,7,7,7,8,2021000001

In [ ]:
df_combined_subject = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d002/combined_data_d002_subject.csv")

In [ ]:
df_combined_ocenka = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d002/combined_data_d002_ocenka.csv')

In [ ]:
df_combined_subject

,GODO,TE,K,NOMP,POL,VOZ,GR1,GR2,GR3,GR4,...,GR28_2,GR28_3,GR28_4,GR28_5,GR29,GR210,GR211,GR212,GR213,GR214
0,2021,19,1,2,2,72,10,10,5,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,31,2,4,2,34,10,10,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,27,2,1,1,65,4,4,3,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,11,2,1,2,53,6,6,7,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,19,1,3,1,16,10,10,10,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47766,2024,63,1,1,1,41,7,7,5,6,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0
47767,2024,75,1,1,2,33,8,7,5,7,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0
47768,2024,33,2,1,1,70,7,7,7,7,...,NaN,NaN,NaN,NaN,2.0,4.0,2.0,2.0,2.0,2.0
47769,2024,55,2,2,2,70,8,8,8,8,...,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0
47770,2024,62,1,2,1,83,9,9,8,8,...,NaN,NaN,NaN,NaN,4.0,4.0,4.0,4.0,4.0,4.0

In [ ]:
df_combined_ocenka

,GODO,TE,K,NOMP,POL,VOZ,GR1,GR2,GR3,GR4,...,GR45_7,GR45_8,GR45_9,GR45_10,GR45_11,GR45_12,GR45_13,GR45_14,GR46,KVINT
0,2021,19,1,2,2,39,3.0,2.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,31,2,4,2,37,5.0,1.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,27,2,1,1,43,4.0,2.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,11,2,1,2,47,3.0,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,19,1,3,1,15,3.0,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47766,2024,63,1,1,1,41,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47767,2024,75,1,1,2,33,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47768,2024,33,2,1,1,70,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47769,2024,55,2,2,2,70,NaN,NaN,NaN,NaN,...,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,NaN
47770,2024,62,1,2,1,83,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_combined_ocenka.to_excel('combined_data_d002_ocenka.xlsx', index=False)
df_combined_subject.to_excel('combined_data_d002_subject.xlsx', index=False)

In [ ]:
df_combined_subject.isna().sum()/df_combined_subject.shape[0] * 100

GODO      0.00000
TE        0.00000
K         0.00000
NOMP      0.00000
POL       0.00000
           ...
GR210    50.00314
GR211    50.00314
GR212    50.00314
GR213    50.00314
GR214    50.00314
Length: 113, dtype: float64

In [ ]:
df_combined_subject.describe()

,GODO,TE,K,NOMP,POL,VOZ,GR1,GR2,GR3,GR4,...,GR28_2,GR28_3,GR28_4,GR28_5,GR29,GR210,GR211,GR212,GR213,GR214
count,47771.000000,47771.000000,47771.000000,47771.000000,47771.000000,47771.000000,47771.000000,47771.000000,47771.000000,47771.000000,...,184.0,154.0,150.0,123.0,23884.000000,23884.000000,23884.000000,23884.000000,23884.000000,23884.000000
mean,2022.499508,42.768814,1.452618,1.680936,1.577401,45.638651,7.791757,7.807582,7.505034,9.414394,...,1.0,1.0,1.0,1.0,2.039524,2.046935,2.049615,2.051038,2.047186,2.040111
std,1.118017,21.117203,0.497755,0.937650,0.493978,17.540551,4.007567,4.343579,4.342818,13.702143,...,0.0,0.0,0.0,0.0,0.405273,0.333127,0.350152,0.350545,0.322619,0.303752
min,2021.000000,10.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2021.000000,27.000000,1.000000,1.000000,1.000000,33.000000,7.000000,7.000000,6.000000,6.000000,...,1.0,1.0,1.0,1.0,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
50%,2022.000000,39.000000,1.000000,1.000000,2.000000,47.000000,7.000000,8.000000,8.000000,7.000000,...,1.0,1.0,1.0,1.0,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
75%,2023.000000,61.000000,2.000000,2.000000,2.000000,60.000000,9.000000,9.000000,9.000000,8.000000,...,1.0,1.0,1.0,1.0,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,2024.000000,79.000000,2.000000,11.000000,2.000000,99.000000,89.000000,89.000000,89.000000,89.000000,...,1.0,1.0,1.0,1.0,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000

In [ ]:
df_combined_ocenka.isna().sum()/df_combined_ocenka.shape[0] * 100

GODO        0.000000
TE          0.000000
K           0.000000
NOMP        0.000000
POL         0.000000
             ...
GR45_12    75.049716
GR45_13    75.315568
GR45_14    75.328128
GR46       75.453727
KVINT      74.978543
Length: 121, dtype: float64

In [ ]:
df_combined_ocenka.describe(  )

,GODO,TE,K,NOMP,POL,VOZ,GR1,GR2,GR3,GR4,...,GR45_7,GR45_8,GR45_9,GR45_10,GR45_11,GR45_12,GR45_13,GR45_14,GR46,KVINT
count,47771.000000,47771.000000,47771.000000,47771.000000,47771.000000,47771.000000,23887.000000,23887.000000,23887.000000,23887.000000,...,11611.000000,11787.000000,11722.000000,12083.000000,11990.000000,11919.000000,11792.000000,11786.000000,11726.000000,11953.000000
mean,2022.499508,42.768814,1.452618,1.680706,1.577275,45.567708,3.180391,1.446310,1.861598,2.004186,...,1.501938,1.318317,1.506569,1.455350,1.660634,1.792264,1.555885,1.738418,1.761470,3.347110
std,1.118017,21.117203,0.497755,0.936824,0.493998,17.596385,0.644887,0.595445,0.866701,0.385059,...,1.183387,0.894469,1.302541,1.216257,1.328204,1.506200,1.216988,1.422426,0.611324,1.384523
min,2021.000000,10.000000,1.000000,1.000000,1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2021.000000,27.000000,1.000000,1.000000,1.000000,33.000000,3.000000,1.000000,1.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
50%,2022.000000,39.000000,1.000000,1.000000,2.000000,47.000000,3.000000,1.000000,2.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,4.000000
75%,2023.000000,61.000000,2.000000,2.000000,2.000000,60.000000,3.000000,2.000000,2.000000,2.000000,...,2.000000,1.000000,1.000000,1.000000,2.000000,3.000000,2.000000,2.000000,2.000000,5.000000
max,2024.000000,79.000000,2.000000,11.000000,2.000000,99.000000,6.000000,3.000000,5.000000,4.000000,...,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,5.000000,5.000000