In [2]:
import pandas as pd

In [ ]:
df_2021 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/t001/2021/2021.csv')
df_2022 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/t001/2022/baza.csv')
df_2023 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/t001/2023/baza.csv')
df_2024 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/t001/2024/baza.csv')

/tmp/ipykernel_486/2304464688.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/t001/2021/2021.csv')
/tmp/ipykernel_486/2304464688.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/t001/2022/baza.csv')
/tmp/ipykernel_486/2304464688.py:3: DtypeWarning: Columns (5,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/t001/2023/baza.csv')
/tmp/ipykernel_486/2304464688.py:4: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2024 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/t001/2024/baza.csv')

In [ ]:
cols = list(df_2021.columns) + list(df_2022.columns) + list(df_2023.columns) + list(df_2024.columns)

In [ ]:
list(set(cols))

['PRICH_ZANV',
 'TE',
 'ORB_PRODOL_1',
 'DH_DATROZH_3',
 'OTVET_LICO',
 'ZAN_RABOTA',
 'PSK_RABOTA',
 'ORB_PKHDHL',
 'DH_GLROSTV',
 'PR_NEPOISK',
 'ZAN_VREMYA_1',
 'DH_DATROZH_2',
 'ORB_MESTOR',
 'K',
 'ZAN_VREMYA_2',
 'RSPD',
 'LP_POTREBL',
 'DOP_RABOTA',
 'DH_PROZHIV_0',
 'DRB_PKHDHL',
 'vosr',
 'ORB_STATUS',
 'ORB_CHISRB',
 'mes',
 'ORB_PRODOL_2',
 'ZAN_RBLPDU',
 'ORB_OTRASL',
 'ORB_TERRIT',
 'DH_POLRESP',
 'ORB_VREMRB',
 'Im_li_d',
 'ORB_OTRASLkod',
 'DH_PROZHIV_5',
 'PROZHSROZH',
 'KOMPT_GRAM',
 'PRD_STATUS',
 'kv',
 'DH_OBRAZOV',
 'ORB_TRDDOG',
 'ORB_PROFES',
 'ZAN_PR_ST',
 'DH_SEMSOST']

In [ ]:
import gc

dfs_to_concat = [df_2021, df_2022, df_2023, df_2024]

df_combined = pd.concat(dfs_to_concat, ignore_index=True, copy=False)

gc.collect()

29

In [ ]:
df_combined.to_csv('combined_data_t001.csv', index=False)

In [ ]:
len(df_2021) + len(df_2022) + len(df_2023) + len(df_2024)

1885110

In [ ]:
len(df_combined)

1885110

In [3]:
df_combined = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/t001/combined_data_t001.csv')

/tmp/ipykernel_2596/480986469.py:1: DtypeWarning: Columns (5,6,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df_combined = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/t001/combined_data_t001.csv')

In [7]:
df_combined.head()

,DH_DATROZH_2,DH_DATROZH_3,DH_GLROSTV,DH_OBRAZOV,DH_POLRESP,DH_PROZHIV_0,DH_PROZHIV_5,DH_SEMSOST,DOP_RABOTA,DRB_PKHDHL,...,TE,ZAN_PR_ST,ZAN_RABOTA,ZAN_RBLPDU,ZAN_VREMYA_1,ZAN_VREMYA_2,vosr,PRICH_ZANV,kv,mes
0,6,1942,1,6,1,2.0,NaN,2,NaN,NaN,...,43,2,2,2,NaN,NaN,78,NaN,NaN,NaN
1,1,1971,1,6,1,4.0,2,2,2.0,NaN,...,35,2,1,2,5.0,40.0,50,NaN,NaN,NaN
2,12,2000,3,5,1,NaN,NaN,1,NaN,NaN,...,47,2,2,2,NaN,NaN,20,NaN,NaN,NaN
3,9,1962,1,4,1,2.0,2,2,1.0,1.0,...,19,2,1,2,7.0,54.0,58,NaN,NaN,NaN
4,1,1981,1,6,1,3.0,3,2,2.0,NaN,...,39,2,1,2,5.0,40.0,40,NaN,NaN,NaN

In [4]:
df_combined.describe()

,DH_DATROZH_2,DH_DATROZH_3,DH_GLROSTV,DH_OBRAZOV,DH_POLRESP,DH_SEMSOST,DOP_RABOTA,DRB_PKHDHL,Im_li_d,K,...,RSPD,TE,ZAN_PR_ST,ZAN_RABOTA,ZAN_RBLPDU,ZAN_VREMYA_1,vosr,PRICH_ZANV,kv,mes
count,1.885110e+06,1.885110e+06,1.885110e+06,1.885110e+06,1.885110e+06,1.885110e+06,914704.000000,27824.000000,1.885110e+06,1.885110e+06,...,1.885110e+06,1.885110e+06,1.885110e+06,1.885110e+06,1.885110e+06,1.257334e+06,1.885110e+06,6089.000000,1.411944e+06,1.412654e+06
mean,6.184101e+00,1.977193e+03,2.102102e+00,5.079646e+00,1.538526e+00,2.067564e+00,1.967422,5.311098,1.903287e+00,1.583955e+00,...,1.768978e+00,4.043293e+01,1.997660e+00,1.332400e+00,1.920084e+00,5.307937e+00,4.484897e+01,1.886681,2.433946e+00,6.499158e+00
std,3.483669e+00,1.678212e+01,1.669339e+00,1.427556e+00,4.985137e-01,7.765348e-01,0.177529,1.404333,2.955669e-01,4.929013e-01,...,9.205514e-01,2.026934e+01,4.832153e-02,4.710737e-01,2.711636e-01,1.098507e+00,1.676486e+01,2.247637,1.109562e+00,3.435108e+00
min,1.000000e+00,1.906000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+01,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.500000e+01,1.000000,1.000000e+00,1.000000e+00
25%,3.000000e+00,1.964000e+03,1.000000e+00,4.000000e+00,1.000000e+00,2.000000e+00,2.000000,6.000000,2.000000e+00,1.000000e+00,...,1.000000e+00,2.300000e+01,2.000000e+00,1.000000e+00,2.000000e+00,5.000000e+00,3.200000e+01,1.000000,1.000000e+00,4.000000e+00
50%,6.000000e+00,1.978000e+03,2.000000e+00,5.000000e+00,2.000000e+00,2.000000e+00,2.000000,6.000000,2.000000e+00,2.000000e+00,...,2.000000e+00,3.900000e+01,2.000000e+00,1.000000e+00,2.000000e+00,5.000000e+00,4.400000e+01,1.000000,2.000000e+00,7.000000e+00
75%,9.000000e+00,1.990000e+03,3.000000e+00,6.000000e+00,2.000000e+00,2.000000e+00,2.000000,6.000000,2.000000e+00,2.000000e+00,...,2.000000e+00,6.100000e+01,2.000000e+00,2.000000e+00,2.000000e+00,6.000000e+00,5.800000e+01,1.000000,3.000000e+00,9.000000e+00
max,1.200000e+01,2.009000e+03,9.000000e+00,9.000000e+00,2.000000e+00,4.000000e+00,2.000000,6.000000,2.000000e+00,2.000000e+00,...,1.200000e+01,7.900000e+01,2.000000e+00,2.000000e+00,2.000000e+00,7.000000e+00,1.160000e+02,8.000000,4.000000e+00,1.200000e+01

In [5]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1885110 entries, 0 to 1885109
Data columns (total 42 columns):
 #   Column         Dtype
---  ------         -----
 0   DH_DATROZH_2   int64
 1   DH_DATROZH_3   int64
 2   DH_GLROSTV     int64
 3   DH_OBRAZOV     int64
 4   DH_POLRESP     int64
 5   DH_PROZHIV_0   object
 6   DH_PROZHIV_5   object
 7   DH_SEMSOST     int64
 8   DOP_RABOTA     float64
 9   DRB_PKHDHL     float64
 10  Im_li_d        int64
 11  K              int64
 12  KOMPT_GRAM     int64
 13  LP_POTREBL     float64
 14  ORB_CHISRB     float64
 15  ORB_MESTOR     float64
 16  ORB_OTRASL     float64
 17  ORB_OTRASLkod  float64
 18  ORB_PKHDHL     float64
 19  ORB_PRODOL_1   float64
 20  ORB_PRODOL_2   float64
 21  ORB_PROFES     object
 22  ORB_STATUS     float64
 23  ORB_TERRIT     float64
 24  ORB_TRDDOG     float64
 25  ORB_VREMRB     float64
 26  OTVET_LICO     int64
 27  PRD_STATUS     float64
 28  PROZHSROZH     float64
 29  PR_NEPOISK     float64
 30  PSK_RABOTA     float64
 31  RSPD           int64
 32  TE             int64
 33  ZAN_PR_ST      int64
 34  ZAN_RABOTA     int64
 35  ZAN_RBLPDU     int64
 36  ZAN_VREMYA_1   float64
 37  ZAN_VREMYA_2   object
 38  vosr           int64
 39  PRICH_ZANV     float64
 40  kv             float64
 41  mes            float64
dtypes: float64(22), int64(16), object(4)
memory usage: 604.1+ MB

In [6]:
df_combined.shape

(1885110, 42)