In [1]:
import pandas as pd

In [ ]:
df_2021 = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/1t_god/2021/2021_1t_god.csv")
df_2022 = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/1t_god/2022/2022_1t_god.csv")
df_2023 = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/1t_god/2023/2023_1t_god.csv")
df_2024 = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/1t_god/2024/sr_1t_god_12_2024.csv")

In [ ]:
import gc

dfs_to_concat = [df_2021, df_2022, df_2023, df_2024]

df_combined = pd.concat(dfs_to_concat, ignore_index=True, copy=False)

del df_2021, df_2022, df_2023, df_2024
gc.collect()

In [ ]:
df_combined = pd.read_csv("/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/1t_god/combined_data.csv")

In [ ]:
df_combined.columns

Index(['ID', 'KCP', 'KATO', 'OKED', 'KZ', 'SPVRP', 'SVNO', 'SSFZP', 'GSUORP',
       'SVR', 'SPNR', 'SP', 'SKRAB', 'SVDOB', 'SSSCHR', 'GR1', 'RMONTH',
       'RYEAR', 'SPTM1', 'VAL_NUM', 'KATO1', 'OKED1', 'OKED2', 'KPOP', 'SPTM',
       'AKT', 'GSGTPE', 'KFS', 'SPVD', 'KOPF', 'KSE', 'KRP'],
      dtype='object')

In [ ]:
missing_values = df_combined.isnull().sum()
missing_values[missing_values > 0].sort_values(ascending=False)

OKED2      30025899
SVDOB      29969842
SSFZP      29272591
SSSCHR     29198713
SPVRP      29168152
SPNR       28854314
SVR        28697233
SVNO       28687511
GSUORP     26722763
OKED1      24582237
VAL_NUM    24582237
KATO1      24582237
SPVD       24582237
KOPF       24582237
KSE        24582237
KFS        24582237
KPOP       24582237
GSGTPE     24582237
AKT        24582237
SPTM       24582237
KRP        24582237
SKRAB      23989194
KZ         20678070
SPTM1      16007912
RMONTH     13165613
RYEAR       7721951
GR1         5443662
SP          3923201
dtype: int64

In [ ]:
missing_percentages = (df_combined.isnull().sum() / len(df_combined)) * 100
display(missing_percentages[missing_percentages > 0].sort_values(ascending=False))

OKED2      100.000000
SVDOB       99.813305
SSFZP       97.491139
SSSCHR      97.245092
SPVRP       97.143310
SPNR        96.098085
SVR         95.574933
SVNO        95.542555
GSUORP      88.999044
OKED1       81.870112
VAL_NUM     81.870112
KATO1       81.870112
SPVD        81.870112
KOPF        81.870112
KSE         81.870112
KFS         81.870112
KPOP        81.870112
GSGTPE      81.870112
AKT         81.870112
SPTM        81.870112
KRP         81.870112
SKRAB       79.895007
KZ          68.867447
SPTM1       53.313681
RMONTH      43.847523
RYEAR       25.717635
GR1         18.129888
SP          13.066057
dtype: float64

In [ ]:
df_combined['OKED2'].unique()

array([nan])

In [ ]:
df_combined['SVDOB'].value_counts()

SVDOB
0.0    30053
2.0    19427
5.0     3628
4.0     2949
Name: count, dtype: int64

In [ ]:
df_combined.to_csv('combined_data.csv', index=False)

In [ ]:
df_combined.shape