In [1]:
import pandas as pd

In [2]:
df_2021 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d006/2021/rio.csv')
df_2022 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d006/2022/rio2022.csv')
df_2023 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d006/2023/rio2023.csv')
df_2024 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d006/2024/rio_2024.csv')

/tmp/ipykernel_614/1665866627.py:3: DtypeWarning: Columns (230) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d006/2023/rio2023.csv')

In [ ]:
import gc

dfs_to_concat = [df_2021, df_2022, df_2023, df_2024]

df_combined = pd.concat(dfs_to_concat, ignore_index=True, copy=False)

gc.collect()

330

In [ ]:
df_combined.to_csv('combined_data_d006.csv', index=False)

In [ ]:
len(df_combined)

46743

In [ ]:
len(df_2021) + len(df_2022) + len(df_2023) + len(df_2024)

46743

In [ ]:
df_combined = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d006/combined_data_d006.csv')

/tmp/ipykernel_852/1300977403.py:1: DtypeWarning: Columns (230) have mixed types. Specify dtype option on import or set low_memory=False.
  df_combined = pd.read_csv('/content/drive/MyDrive/Datathon2026/synthetic_microdata_2021-2024_20260921/d006/combined_data_d006.csv')

In [ ]:
df_combined.to_excel('combined_data_d006.xlsx', index=False)

In [ ]:
df_combined.describe()

,TE,K,TIP_J,VLAD1,J_PL,KOL_K,OB_PL,U1,U2,U3,...,TDP39,TDP40,TDP41,TDP42,TDP43,TDP44,TDP45,TDP46,ZT,NOMER
count,46743.000000,46743.000000,46743.000000,46743.000000,46743.000000,46743.000000,46743.000000,46743.0,46743.000000,46743.000000,...,750.000000,8608.000000,360.000000,617.000000,2434.000000,5120.000000,465.000000,229.000000,46739.000000,4.674300e+04
mean,42.701346,1.457737,2.483024,1.182765,49.871596,2.919560,71.559100,1.0,1.786727,1.508590,...,0.946667,1.087825,0.900000,0.928687,0.986442,1.004297,0.898925,0.864629,1.122082,2.022507e+09
std,21.066479,0.498216,1.415833,0.623338,26.799169,1.112587,33.685526,0.0,0.409623,0.499932,...,0.461996,0.324372,0.680816,0.498150,0.269380,0.177844,0.591334,0.890504,0.366425,1.117445e+06
min,10.000000,1.000000,1.000000,1.000000,10.000000,1.000000,12.000000,1.0,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.021000e+09
25%,27.000000,1.000000,1.000000,1.000000,32.000000,2.000000,49.000000,1.0,2.000000,1.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,2.022000e+09
50%,39.000000,1.000000,3.000000,1.000000,43.000000,3.000000,63.000000,1.0,2.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.022012e+09
75%,61.000000,2.000000,4.000000,1.000000,60.000000,4.000000,84.000000,1.0,2.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.024000e+09
max,79.000000,2.000000,5.000000,7.000000,514.000000,14.000000,463.000000,1.0,2.000000,2.000000,...,3.000000,4.000000,3.000000,2.000000,4.000000,3.000000,4.000000,3.000000,6.000000,2.024012e+09

In [ ]:
df_combined.isna().sum()/len(df_combined) * 100

TE        0.000000
K         0.000000
TIP_J     0.000000
VLAD1     0.000000
J_PL      0.000000
           ...
TDP44    89.046488
TDP45    99.005199
TDP46    99.510087
ZT        0.008557
NOMER     0.000000
Length: 247, dtype: float64

In [8]:
print(df_2021[df_2021['NOMER'] == 2021000001])

   TE  K  TIP_J  VLAD1  J_PL  KOL_K  OB_PL  U1  U2  U3  ...  TDP39  TDP40  \
0  19  1      4      1    39      2     62   1   2   2  ...    NaN    NaN

   TDP41  TDP42  TDP43  TDP44  TDP45  TDP46  ZT       NOMER
0    NaN    NaN    NaN    NaN    NaN    NaN   3  2021000001

[1 rows x 247 columns]